### PR TITLE
fix(dashboard): fix resizing issue

### LINKED ISSUE #573: Dashboard: resize bug
*Resize bug*

1. add 2 widgets
2. select both widgets
3. resize them down to 0 height and width
4. resize them up to some larger height and width
    1. the widgets are now both full size.
    2. (works with any amount of widgets in selection)

### PR DESCRIPTION
**Pull request by square-li**
## Overview
Switched to a new model to calcuate resizing. Now resizing is based on the changes of selection boxes to ensure group resizing doesn't change relative sizes&positions of widgets in the group.

chrome-capture-2023-2-17

Also renamed a few helper functions to reflex its purposes.

fix #573 

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

### CODE REVIEW

File: packages/dashboard/src/util/resizeSelectionBox.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+  }
+  if (anchor.includes('left')) {
+    // don't allow the selection box to be smaller than the minimum width
+    if (newRect.width - vector.x >= MIN_WIDTH) {
+      newRect.x += vector.x;
+      newRect.width -= vector.x;
+    }
+  }
+  if (anchor.includes('right')) {
+    newRect.width += vector.x;
```
Comment (jmbuss) [inline packages/dashboard/src/util/resizeSelectionBox.ts:35]: should we do a min width check here too? The vector can be negative

Comment (square-li) [reply packages/dashboard/src/util/resizeSelectionBox.ts:35]: width/height checking is at end of the function by `rectWithinMin`

Comment (square-li) [reply packages/dashboard/src/util/resizeSelectionBox.ts:35]: We only need to check if x/y are moved here

File: packages/dashboard/src/util/resizeSelectionBox.ts [hunk 2]
```diff
@@ -0,0 +1,42 @@
+import type { Position, Rect } from '~/types';
+import type { Anchor } from '~/store/actions';
+
+const MIN_WIDTH = 2;
```
[the remark this answers is not in the document]
Comment (jmbuss) [reply packages/dashboard/src/util/resizeSelectionBox.ts:4]: ahh ok cool. didn't know if there was some edge case that we were handling that required a specific size

File: packages/dashboard/src/util/resizeSelectionBox.ts (hunk 1 above)
Comment (jmbuss) [reply packages/dashboard/src/util/resizeSelectionBox.ts:35]: so the specific checks on left and top are there to prevent the x value from pushing?

File: packages/dashboard/src/util/resizeSelectionBox.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (square-li) [reply packages/dashboard/src/util/resizeSelectionBox.ts:4]: I think it could give more spaces between anchors so they don't get stacked

File: packages/dashboard/src/util/resizeSelectionBox.ts (hunk 1 above)
Comment (square-li) [reply packages/dashboard/src/util/resizeSelectionBox.ts:35]: Yes. So if widget doesn't get resized on width or height, don't move the origin point (x,y).

Comment (square-li) [reply packages/dashboard/src/util/resizeSelectionBox.ts:35]: we only need to check moving from top or left, since only these two directions modify x/y.

Comment (jmbuss) [reply packages/dashboard/src/util/resizeSelectionBox.ts:35]: gotcha, perfect!

**Review by jmbuss — APPROVED** [review]

**Review by diehbria — APPROVED** [review]
